<html><head></head><body><h1 id="Selenium-报错ValueError解决"><a href="http://example.com/2024/03/24/selenium/#Selenium-%E6%8A%A5%E9%94%99ValueError%E8%A7%A3%E5%86%B3" class="headerlink" title="Selenium 报错ValueError解决"></a>Selenium 报错ValueError解决</h1><ul><li><p>错误<br/>  在python中使用selenium进行网页自动化/爬虫操作时，执行下面语句</p>  <figure class="highlight python"><table><tbody><tr><td class="gutter"><pre><span class="line">1</span><br/><span class="line">2</span><br/></pre></td><td class="code"><pre><span class="line"><span class="keyword">from</span> selenium <span class="keyword">import</span> webdriver</span><br/><span class="line">driver = webdriver.Edge()</span><br/></pre></td></tr></tbody></table></figure><p>  可能会报错：ValueError: Timeout value connect was ……, but it must be an int, float or None…..(/- -)/</p></li><li><p>原因<br/>出错原因：selenium当前版本与urllib3版本不兼容╮（﹀_﹀）╭</p></li><li><p>解决方法<br/>只需要更新为最新版本的selenium与urllib3即可Σ( ° △ °|||)︴</p><figure class="highlight python"><table><tbody><tr><td class="gutter"><pre><span class="line">1</span><br/><span class="line">2</span><br/></pre></td><td class="code"><pre><span class="line">pip install -U selenimu</span><br/><span class="line">pip install -U urllib3</span><br/></pre></td></tr></tbody></table></figure></li></ul></body></html>